TARGET := sf-foundation
BUILD := build
LIBBUTANO := ../.tools/butano/butano
PYTHON := python3
SOURCES := src generated
INCLUDES := include ../game
DATA :=
GRAPHICS := graphics
AUDIO := audio
AUDIOBACKEND := maxmod
DMGAUDIO :=
DMGAUDIOBACKEND := null
ROMTITLE := SF MONSTERS
ROMCODE := SFMM
USERFLAGS :=
USERCXXFLAGS :=
USERASFLAGS :=
USERLDFLAGS :=
USERLIBDIRS :=
USERLIBS :=
DEFAULTLIBS :=
STACKTRACE :=
ifndef LIBBUTANOABS
export LIBBUTANOABS := $(realpath $(LIBBUTANO))
endif
include $(LIBBUTANOABS)/butano.mak
