voice_group birch_lab
	voice_directsound 60, 0, SF_Clinic_flute, 96, 220, 180, 100
	voice_directsound 60, 0, SF_Clinic_bass, 255, 0, 230, 90
	voice_directsound 60, 0, SF_Clinic_major7, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Clinic_minor7, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Clinic_guitar, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Clinic_kick, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Clinic_brush, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Clinic_shaker, 255, 0, 230, 40
