	.align 2
SF_Clinic_flute::
	.incbin "sound/sf_clinic/flute.bin"
	.align 2
SF_Clinic_bass::
	.incbin "sound/sf_clinic/bass.bin"
	.align 2
SF_Clinic_major7::
	.incbin "sound/sf_clinic/major7.bin"
	.align 2
SF_Clinic_minor7::
	.incbin "sound/sf_clinic/minor7.bin"
	.align 2
SF_Clinic_guitar::
	.incbin "sound/sf_clinic/guitar.bin"
	.align 2
SF_Clinic_kick::
	.incbin "sound/sf_clinic/kick.bin"
	.align 2
SF_Clinic_brush::
	.incbin "sound/sf_clinic/brush.bin"
	.align 2
SF_Clinic_shaker::
	.incbin "sound/sf_clinic/shaker.bin"
