voice_group vs_wild
	voice_directsound 60, 0, SF_Wild_lead, 255, 0, 230, 90
	voice_directsound 60, 0, SF_Wild_bass, 255, 0, 230, 90
	voice_directsound 60, 0, SF_Wild_major, 255, 0, 230, 90
	voice_directsound 60, 0, SF_Wild_minor, 255, 0, 230, 90
	voice_directsound 60, 0, SF_Wild_answer, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Wild_kick, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Wild_snare, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Wild_hat, 255, 0, 230, 40
