	.align 2
SF_Wild_lead::
	.incbin "sound/sf_wild/lead.bin"
	.align 2
SF_Wild_bass::
	.incbin "sound/sf_wild/bass.bin"
	.align 2
SF_Wild_major::
	.incbin "sound/sf_wild/major.bin"
	.align 2
SF_Wild_minor::
	.incbin "sound/sf_wild/minor.bin"
	.align 2
SF_Wild_answer::
	.incbin "sound/sf_wild/answer.bin"
	.align 2
SF_Wild_kick::
	.incbin "sound/sf_wild/kick.bin"
	.align 2
SF_Wild_snare::
	.incbin "sound/sf_wild/snare.bin"
	.align 2
SF_Wild_hat::
	.incbin "sound/sf_wild/hat.bin"
