voice_group littleroot
	voice_directsound 60, 0, SF_Ocean_bell, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Ocean_bass, 255, 0, 230, 90
	voice_directsound 60, 0, SF_Ocean_major, 255, 0, 230, 90
	voice_directsound 60, 0, SF_Ocean_minor, 255, 0, 230, 90
	voice_directsound 60, 0, SF_Ocean_pluck, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Ocean_kick, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Ocean_snare, 255, 0, 230, 40
	voice_directsound 60, 0, SF_Ocean_hat, 255, 0, 230, 40
