	.align 2
SF_Ocean_bell::
	.incbin "sound/sf_ocean/bell.bin"
	.align 2
SF_Ocean_bass::
	.incbin "sound/sf_ocean/bass.bin"
	.align 2
SF_Ocean_major::
	.incbin "sound/sf_ocean/major.bin"
	.align 2
SF_Ocean_minor::
	.incbin "sound/sf_ocean/minor.bin"
	.align 2
SF_Ocean_pluck::
	.incbin "sound/sf_ocean/pluck.bin"
	.align 2
SF_Ocean_kick::
	.incbin "sound/sf_ocean/kick.bin"
	.align 2
SF_Ocean_snare::
	.incbin "sound/sf_ocean/snare.bin"
	.align 2
SF_Ocean_hat::
	.incbin "sound/sf_ocean/hat.bin"
